<a href="https://colab.research.google.com/github/jomit-mathew-PA/DATA_SCIENCE/blob/main/WALLMART_SALES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#step1 import all the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing  import StandardScaler,PolynomialFeatures

In [2]:
# get the data
df=pd.read_csv("Walmart_Sales.csv")
print(df)
df.head()

      Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1641957.44             1        38.51       2.548
2         1  19-02-2010    1611968.17             0        39.93       2.514
3         1  26-02-2010    1409727.59             0        46.63       2.561
4         1  05-03-2010    1554806.68             0        46.50       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  28-09-2012     713173.95             0        64.88       3.997
6431     45  05-10-2012     733455.07             0        64.89       3.985
6432     45  12-10-2012     734464.36             0        54.47       4.000
6433     45  19-10-2012     718125.53             0        56.47       3.969
6434     45  26-10-2012     760281.43             0        58.85       3.882

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  192.013558         8.684
6431  192.170412         8.667
6432  192.327265         8.667
6433  192.330854         8.667
6434  192.308899         8.667

[6435 rows x 8 columns]

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

In [4]:
# drop the unwanted columns
df.drop(columns=["Date"],inplace=True)
print(df)

      Store  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price         CPI  \
0         1    1643690.90             0        42.31       2.572  211.096358
1         1    1641957.44             1        38.51       2.548  211.242170
2         1    1611968.17             0        39.93       2.514  211.289143
3         1    1409727.59             0        46.63       2.561  211.319643
4         1    1554806.68             0        46.50       2.625  211.350143
...     ...           ...           ...          ...         ...         ...
6430     45     713173.95             0        64.88       3.997  192.013558
6431     45     733455.07             0        64.89       3.985  192.170412
6432     45     734464.36             0        54.47       4.000  192.327265
6433     45     718125.53             0        56.47       3.969  192.330854
6434     45     760281.43             0        58.85       3.882  192.308899

      Unemployment
0            8.106
1            8.106
2            8.106
3            8.106
4            8.106
...            ...
6430         8.684
6431         8.667
6432         8.667
6433         8.667
6434         8.667

[6435 rows x 7 columns]

In [5]:
model=LinearRegression()

In [6]:
x=df[["Fuel_Price","Temperature","CPI","Holiday_Flag","Unemployment",'Store']]
y=df["Weekly_Sales"]
# split the data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)
# create an object for standardscaler
std=StandardScaler()
# using the fit_transform
std_train=std.fit_transform(xtrain)
# by using the polynomial features
poly=PolynomialFeatures(degree=5)
xpoly=poly.fit_transform(std_train)
model=LinearRegression()
model.fit(xpoly,ytrain)
# testing the data
xtest_scale=std.transform(xtest)
xtestpoly=poly.transform(xtest_scale)
# predicting the value
ypred=model.predict(xtestpoly)
r2_score(ytest,ypred)

0.600068796588763